Return false when cache cp failed

diff --git a/task/cache/0.1/cache.yaml b/task/cache/0.1/cache.yaml
--- a/task/cache/0.1/cache.yaml
+++ b/task/cache/0.1/cache.yaml
@@ -92,9 +92,17 @@ spec:
 
           # If object is directory. (Depends on 'PRE ' suffix now)
           if aws s3 ls "$(params.bucket)/$(params.key)/$path" | head | grep 'PRE ' ; then
-            aws s3 cp "$(params.bucket)/$(params.key)/$path" "$(workspaces.source.path)/$path" --recursive
+            if ! aws s3 cp "$(params.bucket)/$(params.key)/$path" "$(workspaces.source.path)/$path" --recursive ; then
+              # Fail to download cache for some reason
+              printf "false" > "$(results.cache-hit.path)"
+              exit
+            fi
           else
-            aws s3 cp "$(params.bucket)/$(params.key)/$path" "$(workspaces.source.path)/$path"
+            if ! aws s3 cp "$(params.bucket)/$(params.key)/$path" "$(workspaces.source.path)/$path" ; then
+              # Fail to download cache for some reason
+              printf "false" > "$(results.cache-hit.path)"
+              exit
+            fi
           fi
         done
 
